### ISSUE TITLE
ae/start unavailable when starting clojure with "lein run"

### ISSUE THREAD

**Issue by raek** [gcv/appengine-magic#10]
I helped thorwil in #clojure to debug a problem with starting the web server. His code looked something like this:

(ns my-ns ...)
;; define a handler, etc
(defn -main [](ae/start my-app))

By adding ":main my-ns" to the project.clj file, one would expect to be able to start the server by running "lein run", but clojure complained about the var ae/start being missing. I looked into the source of appengine-magic.core and found that it does something similar to "browser sniffing" in the javascript world, i.e. it conditionally loads code depending on what environment you are in. This seems a bit hackish to me. I guess this is about not including that code in production, but wouldn't it be better if the user could choose himself whether he wants to be able to start a local server? Perhaps this could be as simple as making core_local its own namespace. If the user wants to load it, he can simply require it. Maybe it could even be in its own dev-dependency jar.

**Comment by gcv** [comment]
Production and non-production environments must load entirely different code because of classloader restrictions on Google's side. Making core_local its own namespace would require the user to change source code before production deployment.

I'll look into supporting `lein run`, but the easiest way to start a non-interactive local server is with `${APP_ENGINE_SDK}/bin/dev_appserver.sh` or `lein appengine-dev-appserver`.

**Comment by thorwil** [comment]
That means my, or I should say raeks's, workaround of having `(load "/appengine_magic/core_local")` above the `-main` `lein run` will call, will cause a failure once deployed?

**Comment by gcv** [comment]
If that code loads as part of the application bootstrapping process, then yes, it will not deploy. You should be able to get away with it if `my-ns` (from your original example) is not part of the application that App Engine sees after it's deployed, i.e., it's there just for the benefit of `lein run` and contains nothing required for the web application itself.

**Comment by gcv** [comment]
I took a look at making `lein run` work, and I don't see any way to distinguish it from the startup initiated by the production App Engine. If you needed this functionality to use appengine-magic with an environment other than the default REPL, swank-clojure, or VimClojure, please explain what you need in more detail. (I'll gladly accept patches to integrate NetBeans, Eclipse, and IDEA Clojure environments.)

**Comment by thorwil** [comment]
Thank you! No, swank-clojure is what I use and I may obsess a bit too much about getting my devel environment up and running with least effort :)
