### ISSUE TITLE
The task "lein appengine-new"

### ISSUE THREAD

**Issue by sekistner** [gcv/appengine-magic#13]
Am i getting something wrong?
What do i have to do to get leiningen running the appeninge-new task, i can't find a hint in the tutorial what modifies it to do so.

**Comment by gcv** [comment]
You need to create a regular Leiningen project using "lein new", then add appengine-magic to its dependencies. Please take a closer look at the "Project setup" section in "Getting Started" in the README file.

**Comment by sekistner** [comment]
I followed this guide, but after the long dependency download process i am stuck at this point. Then lein doesn't know the command, am i probably using the wrong lein script file?

Thanks for the quick answer anyway.

**Comment by gcv** [comment]
1. Please verify that you are using Leiningen 1.5.0 (run `lein version`, if it's an earlier version, run `lein upgrade`).
2. Create a new project: `lein new mytest`.
3. Use the following `project.clj` file:
   
      (defproject mytest "1.0.0-SNAPSHOT"
        :dependencies [[org.clojure/clojure "1.2.1"]]
        :dev-dependencies [[appengine-magic "0.4.0"]])
4. Run `lein deps`.
5. Delete `mytest/src/core.clj` (appengine-magic will create a better default for you).
6. Run `lein appengine-new`.

**Comment by sekistner** [comment]
sry for my late answer,
everything worked well following your description.
The version was 1.5.0 so i don't know what exactly went wrong.

proceed with your great work
