### ISSUE TITLE
Lacking documentation / obvious way to do multiple file upload

### ISSUE THREAD

**Issue by thorwil** [gcv/appengine-magic#17]
Implementing an upload form for single files is straightforward. Sadly things become more complicated for multiple file upload. An example or info on potential caveats in the development environment would be nice.

Easy to add the `multiple` attribute to a file input. My current understanding is that you need a new generated upload-url for every single file, which means Javascript is required.  My best attempt so far, with my nearly non-existent understanding of JS, parts taken from several sources:

```
...
<input type="file" name="files" multiple />

<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("jquery", "1.4");
</script>

<script type="text/javascript">
  input = $('[name="files"]')[0]

  input.addEventListener("change", function () {
   traverseFiles(this.files);
  }, false);

  function traverseFiles (files) {
    for (var i=0, l=files.length; i<l; i++) {
      prepareUpload(files[i]);
    };
  };

  function prepareUpload (file) {
    $.get('/admin/generate_upload_url', function (url) {
      uploadFile(file, url);
    });
  };

  function uploadFile (file, url) {
    xhr = new XMLHttpRequest();
    xhr.open("post", url, true);

    var boundary = "AJAX--------------" + (new Date).getTime();
    var contentType = "multipart/form-data; boundary=" + boundary;
    xhr.setRequestHeader("Content-Type", contentType);
    xhr.setRequestHeader("X-File-Name", file.fileName);
    xhr.setRequestHeader("X-File-Size", file.fileSize);
    xhr.setRequestHeader("X-File-Type", file.type);

    xhr.send(file);
    // also tried: xhr.sendAsBinary(file);
};
</script>
...
```

Clojure routing:

```
    (ns tlog.core
    (:require [appengine-magic.core :as ae]
          [net.cgrand.enlive-html :as en]
          [ring.util.response :as rsp]
          [tlog.models :as models]
          [tlog.views :as views]
          [appengine-magic.services.blobstore :as blobs])
    (:use ring.middleware.params
      net.cgrand.moustache))

; Validators for serving handler left out

(defn note-blobs
  [request]
  ;(let [b-map (blobs/uploaded-blobs request)]
  ;  (models/save-blobs b-map))
  (println "NOTE-BLOBS")
  (blobs/callback-complete request "/admin/file_done"))

(defn file-done
  [request]
  (println "FILE-DONE")
  (rsp/response  "OK"))

(defn serve-file
  "Take a __BlobInfo__ key and request, serve file from blobstore."
  [key request]
  (blobs/serve request key))

(def tlog-app-handler
     (app
          ["admin" &] {:get (app
             ; File upload form
             ["file"] (views/file-form)

             ["generate_upload_url"]
             (-> (blobs/upload-url "/admin/file_callback") rsp/response constantly)

             :post (app
                ["file_callback"] (-> note-blobs wrap-params)

                ["file_done"] (-> file-done wrap-params)))}

      ; Serve files from the blobstore
      [[name valid-filename-to-blob-key]] {:get (partial serve-file name)}))

(ae/def-appengine-app tlog-app #'tlog-app-handler)
```

This seems to work until to the point where the success handler should be called. That is, `note-blobs` is entered, but `file-done` isn't.

**Comment by gcv** [comment]
Just to be clear: you want to upload multiple files from a single `<input type="file">` field? Just FYI, that's an experimental HTML5 feature, not widely supported in web browsers. Most sites which allow this use a hybrid Flash mechanism to pull it off (see, e.g., SWFUpload or Plupload).

Traditionally, multiple file upload uses an individual `<input>` element per file, combined with a little UI ingenuity and JavaScript to add and remove the required number of tags. The appengine-magic README has a simple (non-JavaScript) example of uploading multiple files in the blobstore documentation section. It does not require a separate upload URL for each file (see the use of `file1`, `file2`, and `file3`).

If you really must have multiple-file upload from a single `<input>`, you do need a few tricks, but they are beyond the scope of appengine-magic. A little Googling turned by [a blog post](http://blog.notdot.net/2010/04/Implementing-a-dropbox-service-with-the-Blobstore-API-part-3-Multiple-upload-support) explaining how to use Plupload with App Engine, but I haven't tried this technique.

**Comment by thorwil** [comment]
Thanks for the detailed answer. Yes, multiple file selection via a single input element.

This is for a very limited user group, so I can count on browser support. I even had this working (at least locally) with Python Appengine.

I've read that blog post and related material several times already. Maybe you have a tip for me, how I could debug this issue, as what I have now doesn't trigger any errors and I need to figure out what's going on?

**Comment by thorwil** [comment]
Success after replacing the final upload function. This works in Firefox 4 and should also work in Chrome (since 7.0) and Safari (since 5.0), since FormData belongs to XMLHttpRequest 2.

```
function uploadFile (file, url) {
  var fd = new FormData();
  fd.append("fileField", file);
  var xhr = new XMLHttpRequest();
  xhr.open("POST", url);
  xhr.send(fd);
};
```
