### ISSUE TITLE
appengine-magic.services.user/login-url fails

### ISSUE THREAD

**Issue by apatil** [gcv/appengine-magic#22]
Hi all,

i have the feeling I'm doing something daft, but  `(appengine-magic.services.user/login-url)` results in

``` clojure
The API package 'user' or call 'CreateLoginURL()' was not found.
  [Thrown class com.google.apphosting.api.ApiProxy$CallNotFoundException]
```

This is with appengine-magic 0.4.2-SNAPSHOT and App Engine SDK 1.5.0.1. It also happened with appengine-magic 0.4.1 and App Engine SDK 1.4.3 . Confusingly, `(appengine-magic.services.user/get-user-service)` works. 

Thanks very much for producing appengine-magic and such good documentation, and thanks in advance for any fixes or answers.

Anand

**Comment by gcv** [comment]
0.4.2-SNAPSHOT doesn't really work yet. I haven't had time to figure out what was broken in the App Engine 1.5.0 release.

Not sure why 0.4.1 doesn't work for you. You started up the server using `ae/serve`, right?

**Comment by apatil** [comment]
Thanks for getting back to me. The problem was in my code and your response set me on the trail to finding it.

In the example I posted, I did indeed forget to use ae/serve. In the actual application, I was trying to define the login-url using `(def login-button (f (user/login-url)))` which, in hindsight, was not so smart.
