### ISSUE TITLE
How to push HTTP parameters through Blobstore file upload

### ISSUE THREAD

**Issue by apatil** [gcv/appengine-magic#23]
Hi again,

I'm trying to create a file upload form that uploads files to the blobstore, then redirects to another URL but carries some form parameters with it. These form parameters carry the session context.

I create the form with Compojure and Appengine-magic as follows:

``` clojure
[:form {:action (blobs/upload-url "/add_file") :method "post" :enctype "multipart/form-data"}
        [:input {:type "file" :name "file-upload"}]
        [:input {:type "hidden" :name "user" :value "anand.prabhakar.patil@gmail.com"]
        [:input {:type "submit" :value text}]]
```

The generated HTML seems to be

``` html
<form action="/_ah/upload/agpjbG91ZHNwb29schwLEhVfX0Jsb2JVcGxvYWRTZXNzaW9uX18YngEM" enctype="multipart/form-data" method="post">
    <input name="file-upload" type="file" />
    <input type="submit" value="Add a file" />
    <input name=":user" type="hidden" value="anand.prabhakar.patil@gmail.com" />
</form>
```

However, the request received by my `"/add_file"` route is

``` clojure
{:remote-addr "127.0.0.1", 
:scheme :http, 
:response #<ResponseWrapper com.google.appengine.api.blobstore.dev.ServeBlobFilter$ResponseWrapper@60f9ccb3>,
:query-params {}, 
:session {}, 
:form-params {}, 
:multipart-params {}, 
:servlet #<HttpServlet$0 appengine_magic.servlet.proxy$javax.servlet.http.HttpServlet$0@2fee2d82>, 
:request-method :post, 
:query-string nil, 
:route-params {}, 
:content-type "text/plain", 
:request #<Request POST /add_job HTTP/1.1
...
}
```

that is, the `?user=anand.prabhakar.patil@gmail.com` that I was hoping for doesn't seem to have made it through the upload. I also can't find it by inspecting the Jetty request in the `:request` field. I'm using `compojure.handler.site`, which handles parameters correctly in other contexts. What's the best way to push the parameters through?

Once again, thanks very much for Appengine-magic and sorry if this is not a good question.

Is it OK to ask questions here on the issues page, or would you prefer them somewhere else?

Anand

**Comment by gcv** [comment]
Right. I looked into this a while ago, and couldn't find a way to force App Engine to preserve any additional form parameters in the upload callback. I also couldn't think of a good way to hack that into appengine-magic.

As a workaround, try saving the extra data in a cookie right before the form submit. Not ideal, but it might work.

Feel free to ask questions here, at least for now.

**Comment by apatil** [comment]
OK, thanks. Do you think it would be a bad idea to store the session in the datastore rather than a cookie? What about doing that throughout the application rather than passing form parameters around?

**Comment by apatil** [comment]
So what I ended up doing was:
- Before the upload, stick the session parameters in memcache
- After the upload, use `appengine-magic.services.blobstore/callback-complete` to redirect to a bounce page
- In the route for the bounce page, read the session parameters out of memcache, put together the URL for the original page with parameters using `hiccup.page-helpers/encode-params` and redirect to it using `ring.util.response/redirect`.

It's fast enough, and allows me to keep passing the session parameters around in form parameters rather than setting cookies.

Anand
