### ISSUE TITLE
Intall broken

### ISSUE THREAD

**Issue by mobileink** [gcv/appengine-magic#27]
lein appengine-new fails with:

Error 
  DOMSource cannot be processed: check that saxon9-dom.jar is on the classpath
Exception in thread "main" net.sf.saxon.trans.XPathException: DOMSource cannot be processed: check that saxon9-dom.jar is on the classpath (NO_SOURCE_FILE:0)

**Comment by gcv** [comment]
What operating system? What version of Leiningen? What version of Java? What is in your `project.clj` file?

**Comment by mobileink** [comment]
On Mon, Jun 27, 2011 at 11:04 AM, gcv <
reply@reply.github.com>wrote:

> What operating system? What version of Leiningen? What version of Java?
> What is in your `project.clj` file?
> 
> Thanks for the quick reply.

OS:  mac os x 10.6.7
Lein:  1.5.2

$ lein version
Leiningen 1.5.2 on Java 1.6.0_24 Java HotSpot(TM) 64-Bit Server VM

project.clj:  (defproject gae "1.0.0-SNAPSHOT"
  :description "FIXME: write description"
  :dependencies [[org.clojure/clojure "1.2.1"]]
  :dev-dependencies [[appengine-magic "0.4.2"]])

Result of running $ lein deps on a freshly created project:

lib/clojure-1.2.1.jar
lib/dev/ contains:
appengine-api-1.0-sdk-1.5.1.jar

appengine-api-labs-1.5.1.jar
appengine-api-stubs-1.5.1.jar
appengine-local-runtime-1.5.1.jar
appengine-local-runtime-shared-1.5.1.jar
appengine-magic-0.4.2.jar
appengine-testing-1.5.1.jar
appengine-tools-api-1.5.1.jar
clojure-1.2.1.jar
commons-codec-1.4.jar
commons-el-1.0.jar
commons-exec-1.1.jar
commons-fileupload-1.2.1.jar
commons-io-1.4.jar
commons-logging-1.0.3.jar
geronimo-jsp_2.1_spec-1.0.1.jar
jasper-runtime-5.0.28.jar
jstl-1.1.2.jar
ring-core-0.3.8.jar
servlet-api-2.5.jar
standard-1.1.2.jar

I suspect the code in appengine_new.clj that tries to use xpath to rewrite
web.xml and appengine-web.xml.  I looked all over the place for
saxon9-dom.jar and could not find it.

A humble suggestion:  xpath is overkill for this; a better approach might be
to use the stringTemplate lib (http://www.stringtemplate.org/).

Thanks,

Gregg

**Comment by gcv** [comment]
This works for me. I'm on Mac OS 10.6.8, though I doubt that's the problem.

Try manually adding it to your project dependencies. Googling around revealed a Maven repository with that file: http://www2.ph.ed.ac.uk/maven2/net/sf/saxon/saxon9-dom/. So add something like this to project.clj:

```
:repositories {"saxon9" "http://www2.ph.ed.ac.uk/maven2"}
:dev-dependencies [[net.sf.saxon/saxon9-dom "9.1.0.8"]]
```

Maybe that'll work. Out of curiosity, did you do anything unusual with your system's Java setup?
