### ISSUE TITLE
tag rebindable vars with ^:dynamic to prepare for Clojure 1.3

### ISSUE THREAD

**Issue by andymoe** [gcv/appengine-magic#29]
I want to shut up the warnings generated when doing `lein appengine-prepare` under Clojure 1.3.0-beta1 such as the following:

Warning: _user-service_ not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic _user-service_ or change the name.`

Most of these warnings come from the code that wraps the specific google appengine services.

I can probably take this one on and submit a patch as long as it's not too much more complicated than it seems to be. I'm pretty new to Clojure but can probably take on this kind of grunt work.

**Comment by gcv** [comment]
By all means. All services definitely need the `^:dynamic` change.

I haven't had time to dive into Clojure 1.3, or into updating appengine-magic for it. I don't know what else might break. If you've been working with 1.3 and App Engine, then any patches, notes, or suggestions you have will be very welcome. I'm particularly concerned about the dynamic rebinding changes breaking the interactive REPL.

**Comment by andymoe** [comment]
Been a bit busy :/ going to try and get to this in the next week.

**Comment by gcv** [comment]
I plan to port appengine-magic to use Clojure 1.3 in the next few weeks. If you have finished this task, I'll be happy to pull your changes into the current v0.4.6 branch (though it might turn into a v0.5.0 release if enough major changes accumulate). If not, no worries, I'll take care of this later.

**Comment by andymoe** [comment]
I see you got to this in the v0.4.6 branch. Apologies for totally dropping the ball.

**Comment by gcv** [comment]
No worries. :) All released in 0.4.6 now.
