### ISSUE TITLE
"not found" error in lein appengine-prepare getDirectoryScanner for lib/dev 

### ISSUE THREAD

**Issue by mblakele** [gcv/appengine-magic#30]
I think I'm following the directions at https://github.com/gcv/appengine-magic README.md correctly, but appengine-prepare hits an error trying to set up the "dev" directory. If I missed a step, thanks in advance for any advice.

To reproduce:

$ pwd
/tmp
$ lein --version
Leiningen 1.6.0 on Java 1.6.0_26 Java HotSpot(TM) 64-Bit Server VM
$ lein new simple-test
Created new project in: /tmp/simple-test
$ cd simple-test
$ rm src/simple_test/core.clj
# edit project.clj to add :dev-dependencies [[appengine-magic "0.4.2"]]

$ cat project.clj
(defproject simple-test "1.0.0-SNAPSHOT"
  :description "FIXME: write description"
  :dependencies [[org.clojure/clojure "1.2.1"]]
  :dev-dependencies [[appengine-magic "0.4.2"]])
$ lein deps
Copying 1 file to /private/tmp/simple-test/lib
Copying 21 files to /private/tmp/simple-test/lib/dev
$ lein appengine-new
making a skeleton for a Google App Engine application
created war directory war
created WEB-INF directory war/WEB-INF
created base entry point servlet /private/tmp/simple-test/src/simple_test/app_servlet.clj
created core namespace file /private/tmp/simple-test/src/simple_test/core.clj
web.xml written to war/WEB-INF/web.xml
appengine-web.xml written to war/WEB-INF/appengine-web.xml
$ lein appengine-prepare

Unexpected results:

preparing App Engine application simple-test for deployment
Compiling simple-test.app_servlet
Compilation succeeded.
Created dir: /private/tmp/simple-test/war/WEB-INF/lib
Copying 1 file to /private/tmp/simple-test/lib
Created /private/tmp/simple-test/simple-test-1.0.0-SNAPSHOT.jar
Moving 1 file to /private/tmp/simple-test/war/WEB-INF/lib
Copying 1 file to /private/tmp/simple-test/war/WEB-INF/lib
Exception in thread "main" /private/tmp/simple-test/lib/dev not found. (NO_SOURCE_FILE:0)
    at clojure.lang.Compiler.eval(Compiler.java:5440)
    at clojure.lang.Compiler.eval(Compiler.java:5391)
    at clojure.core$eval.invoke(core.clj:2382)
    at clojure.main$eval_opt.invoke(main.clj:235)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$script_opt.invoke(main.clj:270)
    at clojure.main$main.doInvoke(main.clj:354)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at clojure.lang.Var.invoke(Var.java:377)
    at clojure.lang.AFn.applyToHelper(AFn.java:172)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
Caused by: /private/tmp/simple-test/lib/dev not found.
    at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:349)
    at org.apache.tools.ant.taskdefs.Copy.execute(Copy.java:404)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:90)
    at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:265)
    at lancet.core$copy.doInvoke(core.clj:153)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at leiningen.appengine_prepare$appengine_prepare.invoke(appengine_prepare.clj:46)
    at clojure.lang.Var.invoke(Var.java:365)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.core$apply.invoke(core.clj:542)
    at leiningen.core$apply_task.invoke(core.clj:228)
    at leiningen.core$_main.doInvoke(core.clj:294)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:542)
    at leiningen.core$_main.invoke(core.clj:297)
    at user$eval42.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:5424)
    ... 11 more

At this point here's the state of my project directory: there is indeed no lib/dev directory.

$ ls -R
README      classes     lib     project.clj src     test        war

./classes:
appengine_magic simple_test

./classes/appengine_magic:
core$appengine_app_id.class             servlet$servlet$fn__134.class
core$appengine_app_version.class            servlet$servlet.class
core$appengine_base_url.class               servlet$set_response_body.class
core$appengine_environment_type.class           servlet$set_response_headers.class
core$def_appengine_app.class                servlet__init.class
core$in_appengine_interactive_mode_QMARK_$fn__43.class  utils$_dash.class
core$in_appengine_interactive_mode_QMARK_.class     utils$copy_stream.class
core$loading__4414__auto__.class            utils$dash_.class
core$open_resource_stream.class             utils$derefify_future$fn__67.class
core__init.class                    utils$derefify_future$reify__69.class
core_google__init.class                 utils$derefify_future.class
servlet                         utils$loading__4414__auto__.class
servlet$adapt_servlet_response.class            utils$os_type.class
servlet$get_headers$fn__95.class            utils$record.class
servlet$get_headers.class               utils$xpath_replace_all.class
servlet$loading__4414__auto__.class         utils$xpath_value$fn__86.class
servlet$make_request_map.class              utils$xpath_value.class
servlet$make_servlet_service_method$fn__131.class   utils__init.class
servlet$make_servlet_service_method.class

./classes/appengine_magic/servlet:
proxy$javax

./classes/appengine_magic/servlet/proxy$javax:
servlet

./classes/appengine_magic/servlet/proxy$javax/servlet:
http

./classes/appengine_magic/servlet/proxy$javax/servlet/http:
HttpServlet$0.class

./classes/simple_test:
app_servlet$_service.class      core$loading__4414__auto__.class
app_servlet$loading__4414__auto__.class core$simple_test_app_handler.class
app_servlet.class           core__init.class
app_servlet__init.class

./lib:
clojure-1.2.1.jar

./src:
simple_test

./src/simple_test:
app_servlet.clj core.clj

./test:
simple_test

./test/simple_test:
test

./test/simple_test/test:
core.clj

./war:
WEB-INF

./war/WEB-INF:
appengine-web.xml   lib         web.xml

./war/WEB-INF/lib:
clojure-1.2.1.jar       simple-test-1.0.0-SNAPSHOT.jar

However, if I clean the project and re-run deps, I do see a dev directory. It looks as if the appengine-prepare task is deleting lib/dev. Is it supposed to do that?

$ lein clean
Cleaning up.
$ lein deps
Copying 1 file to /private/tmp/simple-test/lib
Copying 21 files to /private/tmp/simple-test/lib/dev
$ ls -R
README      classes     lib     project.clj src     test        war

./classes:

./lib:
clojure-1.2.1.jar   dev

./lib/dev:
appengine-api-1.0-sdk-1.5.1.jar         commons-exec-1.1.jar
appengine-api-labs-1.5.1.jar            commons-fileupload-1.2.1.jar
appengine-api-stubs-1.5.1.jar           commons-io-1.4.jar
appengine-local-runtime-1.5.1.jar       commons-logging-1.0.3.jar
appengine-local-runtime-shared-1.5.1.jar    geronimo-jsp_2.1_spec-1.0.1.jar
appengine-magic-0.4.2.jar           jasper-runtime-5.0.28.jar
appengine-testing-1.5.1.jar         jstl-1.1.2.jar
appengine-tools-api-1.5.1.jar           ring-core-0.3.8.jar
clojure-1.2.1.jar               servlet-api-2.5.jar
commons-codec-1.4.jar               standard-1.1.2.jar
commons-el-1.0.jar

./src:
simple_test

./src/simple_test:
app_servlet.clj core.clj

./test:
simple_test

./test/simple_test:
test

./test/simple_test/test:
core.clj

./war:
WEB-INF

./war/WEB-INF:
appengine-web.xml   lib         web.xml

./war/WEB-INF/lib:
clojure-1.2.1.jar       simple-test-1.0.0-SNAPSHOT.jar

**Comment by gcv** [comment]
I can't reproduce this. I'm using Leiningen 1.6.1, maybe try upgrading?

Make sure that `lib/dev/` exists before running `lein appengine-prepare`. Also make sure your `classes/` directory is empty.

**Comment by mblakele** [comment]
You can see that classes is empty and dev exists after the clean + deps tasks run, at the bottom of my initial report. That does not change the behavior, and an identical exception is thrown.

Here's 1.6.1: looks like it fixes the problem. I think it might have been https://github.com/technomancy/leiningen/issues/221

$ lein --version
Leiningen 1.6.1 on Java 1.6.0_26 Java HotSpot(TM) 64-Bit Server VM
$ lein clean && lein deps
Cleaning up.
Copying 1 file to /private/tmp/simple-test/lib
Copying 21 files to /private/tmp/simple-test/lib/dev

$ ls -R
README      classes     lib     project.clj src     test        war

./classes:

./lib:
clojure-1.2.1.jar   dev

./lib/dev:
appengine-api-1.0-sdk-1.5.1.jar         commons-exec-1.1.jar
appengine-api-labs-1.5.1.jar            commons-fileupload-1.2.1.jar
appengine-api-stubs-1.5.1.jar           commons-io-1.4.jar
appengine-local-runtime-1.5.1.jar       commons-logging-1.0.3.jar
appengine-local-runtime-shared-1.5.1.jar    geronimo-jsp_2.1_spec-1.0.1.jar
appengine-magic-0.4.2.jar           jasper-runtime-5.0.28.jar
appengine-testing-1.5.1.jar         jstl-1.1.2.jar
appengine-tools-api-1.5.1.jar           ring-core-0.3.8.jar
clojure-1.2.1.jar               servlet-api-2.5.jar
commons-codec-1.4.jar               standard-1.1.2.jar
commons-el-1.0.jar

./src:
simple_test

./src/simple_test:
app_servlet.clj core.clj

./test:
simple_test

./test/simple_test:
test

./test/simple_test/test:
core.clj

./war:
WEB-INF

./war/WEB-INF:
appengine-web.xml   lib         web.xml

./war/WEB-INF/lib:
clojure-1.2.1.jar       simple-test-1.0.0-SNAPSHOT.jar

$ lein appengine-prepare
preparing App Engine application simple-test for deployment
Compiling simple-test.app_servlet
Compilation succeeded.
Deleting directory /private/tmp/simple-test/war/WEB-INF/lib
Created dir: /private/tmp/simple-test/war/WEB-INF/lib
Copying 1 file to /private/tmp/simple-test/lib
Overriding previous definition of reference to simple-test
Overriding previous definition of reference to dependency.fileset
Copying 21 files to /private/tmp/simple-test/lib/dev
Created /private/tmp/simple-test/simple-test-1.0.0-SNAPSHOT.jar
Moving 1 file to /private/tmp/simple-test/war/WEB-INF/lib
Copying 1 file to /private/tmp/simple-test/war/WEB-INF/lib
Copying 8 files to /private/tmp/simple-test/war/WEB-INF/lib
