### ISSUE TITLE
Add support for pre/post to ds/defentity

### ISSUE THREAD

**Issue by Folcon** [gcv/appengine-magic#37]
Would you consider adding support for a pre and post hook to ds/defentity? So if these are defined then a given function can be called before saving (pre-save) and after loading (post-load)?

Kind Regards,
Folcon

**Comment by gcv** [comment]
Seems reasonable. These functions wouldn't be atomic, though. I'll add this to the list of things to do in the future, but in the meanwhile, patches are welcome.

**Comment by Folcon** [comment]
Thank you, I'll have a bash at it and if I can get it working on my end I'll be happy to submit it.

**Comment by jurrchen** [comment]
Folcon: I actually have a patch (been lazy about cleaning it up and submitting) that adds in post-save callbacks. It wouldn't be hard to add in pre-save and post-load, but what is the use-case for those callbacks (just curious)?

**Comment by Folcon** [comment]
Oh, mostly to do a regular transformation on the code before saving/after loading the code. So things such as encryption before saving/decryption after loading the data structures or even altering how I store the data in the datastore vs how I use it in the application.

**Comment by Folcon** [comment]
I've come across a use case actually, I've been using Joda time and storing the objects using ^:clj however that doesn't really work very well as I need to eval to recover the object, I could simply use pre-save and post-load to convert to and from longs without having to have extra conversion functions on either side.

If this is too much of a bother, don't worry about it. I can manage ;)...

**Comment by gcv** [comment]
I also use Joda-Time, but I generally convert to java.util.Date objects (since App Engine can handle them). I can see the appeal of supporting pre-load and post-load to do the conversion automatically.

**Comment by Folcon** [comment]
It does fix a few problems :).

**Comment by gcv** [comment]
What semantics would you expect from these callbacks?

before-save and after-load are easy enough. They take and return an entity record (possibly with transformed fields).

What about after-save and before-load, though? I don't know what work they need to perform on the objects being saved or loaded. Is there a strong enough argument for adding them just so they could perform operations with side effects?

**Comment by Folcon** [comment]
Good point, realistically speaking I believe that it's only worthwhile having a before-save and after-load hook as their have well defined behaviour and it's not a good idea to just go jumping in and adding functionality just because. Give them some sensible names and that should be that. If there later appear use cases for the other two functions then I believe we can consider them separately later.

BTW Thank you very much for the consideration. This is more like a pet annoyance than a major feature, but I do feel that I would not be alone in feeling this is useful.

**Comment by gcv** [comment]
I committed a sample implementation of before-save and after-load to the v0.4.6 experimental branch and made an artifact available as 0.4.6-SNAPSHOT. Give it a shot. If it seems stable, I'll make it part of the next version. I didn't make it part of today's 0.4.5 release; it just doesn't seem like a safe enough change to push out along with App Engine SDK 1.5.4 support.

**Comment by Folcon** [comment]
That's reasonable, I'll give it a test run tomorrow.

Thanks

**Comment by gcv** [comment]
Feature released with appengine-magic 0.4.6.
