### ISSUE TITLE
countEntites 1000 limit

### ISSUE THREAD

**Issue by bartojs** [gcv/appengine-magic#42]
Hi

datastore counts are lmited to 1000 due to deprecated PreparedQuery countEntities method

in javadoc:
@Deprecated int countEntities() Deprecated. Use countEntities(FetchOptions) instead.

In apopengine issues 3671
http://code.google.com/p/googleappengine/issues/detail?id=3671

Just adding the fetch-options-object used for the query works for me
Cheers Justin
# 

From 2f3bc1d8e7655197b29c838d2f4302af0bb4e272 Mon Sep 17 00:00:00 2001
From: justin barton
Date: Sat, 27 Aug 2011 00:30:07 +1200
Subject: [PATCH] use fetchoptions in result count to avoid 1000 limit in counts

---

 src/appengine_magic/services/datastore.clj |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

diff --git a/src/appengine_magic/services/datastore.clj b/src/appengine_magic/services/datastore.clj
index c66dd33..18d4775 100644
--- a/src/appengine_magic/services/datastore.clj
+++ b/src/appengine_magic/services/datastore.clj
@@ -460,7 +460,7 @@
         result-type (if (and (instance? Class kind) (extends? EntityProtocol kind))
                         kind
                         entity-record-type)
-        result-count (.countEntities prepared-query)]
-        result-count (.countEntities prepared-query fetch-options-object)]
   (cond count-only? result-count
         (zero? result-count) (list)
         :else (let [results (seq (.asIterable prepared-query fetch-options-object))
  --
  1.7.4

**Comment by gcv** [comment]
Thanks, I'll include your patch in the next version.

**Comment by gcv** [comment]
I committed this change into my local repository, will push to GitHub in the next few days.
