### ISSUE TITLE
new* with select-keys not working

### ISSUE THREAD

**Issue by roti** [gcv/appengine-magic#43]
Hi,

When using dataservices new\* together with select-keys I get an java.lang.IllegalArgumentException:

(ds/new\* Order {:id 100})                #works fine

(ds/new\* Order (select-keys {:a 100 :b 200 :id 5000} '(:id)))                     #throws java.lang.IllegalArgumentException

My apologies if this is a false bug, I'm a greenhorn in clojure matters.

Cheers,
Razvan

**Comment by gcv** [comment]
This happens because ds/new\* is a macro and does not evaluate the second argument when it looks like a function call. I'll look into fixing this for the next version of appengine-magic, but I'm not entirely sure this is a safe change.

**Comment by roti** [comment]
The same thing happens if instead of a select-keys, I pass a variable (e.g. parameter of a function) which contains a map. It looks like new\* works only if I pass the map as a {} syntax contruct, which is kind of weird. Here the code that breaks:

(defn new-orders [params](let [obj %28ds/new* Order params%29]
 %28ds/save! obj%29
 %28map-xml obj)))

Trying to compile this function throws the IllegalArgumentException.

Razvan

**Comment by gcv** [comment]
Yes, I know.

`new*` is not necessary unless you need to use its `:parent` support to create entity groups, although I can see its appeal as a general entity creation mechanism. Since your example does not require entity groups, I suggest using the `record` macro defined in `appengine-magic.utils` directly: `(record Order params)`.

**Comment by gcv** [comment]
This isn't a false bug, but it's a pretty tough nut to crack. A macro which does the right thing under all circumstances is tricky to write and would most likely be fairly slow. Commit 9e0cd43 explains the issue in more detail.

I recommend avoiding new\* unless you need entity group creation. I'll work on providing an alternative, and will deprecate new\* in a future version of appengine-magic.

**Comment by roti** [comment]
Ok. Thanks. I don't need entity groups (at least for the moment), so I'm currently avoiding new*.
