### ISSUE TITLE
Please support task deletion

### ISSUE THREAD

**Issue by thorwil** [gcv/appengine-magic#47]
I know there was no programmatic way, initially, but now there's purge() and deleteTask():
http://code.google.com/appengine/docs/java/taskqueue/overview.html#Deleting_Tasks

In any case `The current App Engine SDK does not seem to have any API calls for removing tasks from a queue, but does support this from the administration console.` needs an update ;)

**Comment by gcv** [comment]
Good call. :)

**Comment by gcv** [comment]
Just implemented this feature in my local repository. Will push to GitHub in the next few days, and this feature will be in the next release.
