### ISSUE TITLE
(ds/retrieve) always returns nil

### ISSUE THREAD

**Issue by markokocic** [gcv/appengine-magic#5]
Hi, I'm trying your Datastore examples from README in swank repl.
I was able to successfully call ds/query, but all calls that depends on ds/retrieve are not working, since ds/retrieve fails to retrieve entity from datastore.

```
user>(ds/defentity Book [^:key isbn, title, author])
user.Author
user> (def will (first (ds/query :kind Author :filter (= :name "Shakespeare, William"))))
#'user/will
user> will
#:user.Author{:name "Shakespeare, William", :birthday nil}
user> (ds/retrieve Author "Shakespeare, William")
nil
user> (ds/exists? Author "Shakespeare, William")
false
```

I'm using clojure-1.3.0-alpha4 and latest appengine-magic from git 0.4.0 branch.

**Comment by gcv** [comment]
Thanks for the report. This is a result of the metadata tag format changes in Clojure 1.3. I committed a (temporary) workaround to v0.4.0 and put a new 0.4.0-SNAPSHOT in Clojars.

You should delete your datastore file (war/WEB-INF/appengine-generated/local_db.bin) before trying the example again. appengine-magic uses metadata tags to track datastore entity keys, and the 1.3-incompatible code did not determine the correct key on the entity, so you ended up with duplicates in your datastore.
