### ISSUE TITLE
Appengine 1.6.3 + support

### ISSUE THREAD

**Issue by cjschroed** [gcv/appengine-magic#55]
My question is: Do you have plans to rev appengine-magic from 1.5.5 to 1.6.x anytime soon? Full text search is coming
and I will need the 1.6.x versions to support it.

As an experiment, I changed the dependencies and the handler mappings in core_local.clj.
There is one serious issue regarding the serving of blobs from the blobstore.
There are minor issues with the datastore, taskqueue, and capabilities admin viewers.
I am a clojure and GAE novice, so I can't evaluate the severity. 
If you have no plans to do it anytime soon, I can keep hacking at it.

P.S. I love your project. It really made getting off the ground in Clojure + GAE easy. ;)

**Comment by gcv** [comment]
I'd very much like to update appengine-magic, but I'm currently short on time. I looked at it when 1.6.0 came out, saw severe breakage, and didn't have time to dig any deeper. I even put appengine-magic up as a suggested project for Google Summer of Code, in the hopes that someone with more time could try to fix it.

I'll gladly incorporate any patches you may have to bring the project up-to-date. If you put your current changes up on GitHub, I'll look at what you have and see what I can do to fix the other problems, or the help you out with it.

**Comment by cjschroed** [comment]
Awesome. I'll tinker with it a bit and see if I can't get it working right.

**Comment by gcv** [comment]
Version 0.5.0 now supports 1.6.3.1. Hope that helps your project.
