### ISSUE TITLE
lein appengine-prepare broken with lein 1.7.0

### ISSUE THREAD

**Issue by galalex** [gcv/appengine-magic#57]
I followed the following steps:
1. lein new coco
2. added :dev-dependencies [[appengine-magic "0.4.7"]]) to project.clj
3. rm src/coco/core.clj
4. lein deps
5. lein appengine-new
6. lein appengine-prepare

> preparing App Engine application coco for deployment
> Compiling coco.app_servlet
> Compilation succeeded.
> Created dir: /tmp/coco/war/WEB-INF/lib
> Copying 1 file to /tmp/coco/lib
> Overriding previous definition of reference to dependency.fileset
> Overriding previous definition of reference to coco
> Copying 20 files to /tmp/coco/lib/dev
> No namespaces to :aot compile listed in project.clj.
> Created /tmp/coco/coco-1.0.0-SNAPSHOT.jar
> Moving 1 file to /tmp/coco/war/WEB-INF/lib
> Copying 1 file to /tmp/coco/war/WEB-INF/lib
> Copying 7 files to /tmp/coco/war/WEB-INF/lib

The jar coco-1.0.0-SNAPSHOT.jar does not contain any classes.
jar -tvf war/WEB-INF/lib/coco-1.0.0-SNAPSHOT.jar

>  70 Thu Mar 15 12:42:36 EDT 2012 META-INF/MANIFEST.MF
>  1416 Thu Mar 15 12:42:36 EDT 2012 META-INF/maven/coco/coco/pom.xml
>    93 Thu Mar 15 12:42:36 EDT 2012 META-INF/maven/coco/coco/pom.properties
>   173 Thu Mar 15 12:40:36 EDT 2012 project.clj

gae/devappserver.sh war:

>  in java.lang.ClassNotFoundException: coco.app_servlet

Adding :aot [coco.core coco.app_servlet] to project.clj and running lein appengine-prepare will add the classes
to the jar. 

However, adding the :aot directive will result in NullPointerException when working in the repl:

> lein clean
> lein repl
> (use 'coco.core)
> (require '[appengine-magic.core :as ae])
> (ae/serve coco-app)

results in NullPointerException   java.io.File.<init> (File.java:389).

If I remove the :aot directive from project.clj, (ae/serve coco-app) starts jetty with no errrors.

I am using lein version 1.7.0. 

Am I missing something or is this behavior a bug ?

**Comment by gcv** [comment]
Looks like something changed in the way the Leiningen jar task works. It does not play well with the appengine-prepare task. Thanks for the bug report. In the meanwhile, an older version of lein should work.

**Comment by gcv** [comment]
This is now fixed in version 0.5.0.

**Comment by galalex** [comment]
Awesome! Thanks for fixing it!
