### ISSUE TITLE
ae architecture

### ISSUE THREAD

**Issue by mobileink** [gcv/appengine-magic#69]
Hi,

In the course of writing a leiningen plugin for appengine-magic (https://github.com/greynolds/gaem) I learned a lot about ae and have a number of suggestions as to future development.  I'm not sure what the appropriate forum is for discussing them, so here I'll just mention one (which qualifies as a bug) and ask how you would prefer to discuss architectural issues if you are interested.

Here's the bug:  appengine-magic.core/start hardcodes a single "handler" as the handler for "/".  This effectively means that only one monolithic servlet is allowed; it makes web.xml irrelevant.  I've messed around with the code a little bit but have not figured out how to remedy this.  It requires more knowledge than I care to acquire about Jetty.

The plugin mentioned above (gaem) demonstrates that this is not necessary - the sample project uses two servlets, and it works on dev_appserver.  But running it via a repl using ae/start exposes problems.  You can only ae/start one servlet at a time, and when you do, that servlet services the entire "/*" tree, despite what web.xml says.  There are a couple of other problems which I'll file separately.

Implementing the plugin has lead me to rethink the entire architecture of appengine-magic - not the internals of the api library, but the packaging of what are essentially separate tools and dev functions as part of ae.  Such stuff could all be split out into a separate library (most likely a leiningen plugin like gaem) leaving a simplified ae lib that does the gae api only.

Before I go any further with this I'd like to get the developer's feedback (and blessing, I hope).  What is your preferred forum for discussing such issues?

Thanks very much for making ae!

-Gregg Reynolds

**Comment by gcv** [comment]
I looked at your plugin. There is definitely room for improvement on
the Leiningen side of things in appengine-magic. At the moment,
Leiningen2 support is simply broken in master, and your plugin seems
like a step in the right direction.

I am not a huge fan of splitting appengine-magic into several pieces.
If your plugin helps resolve the current problems, why not just use it
to replace the current one? I didn't dive into lein2 yet, but is there
a way to generate two separate artifacts from one project, one with
just leiningen tasks and one with the App Engine library?

As for running multiple servlets with web.xml, I initially wanted to
add this feature, but it was, as you discovered, quite a bit of work:
parsing web.xml, extracting the needed path mappings, and inserting
them into Jetty. It's quite doable, but I never needed it.

**Comment by mobileink** [comment]
On Mar 29, 2013, at 9:59 AM, Constantine Vetoshev notifications@github.com wrote:

> I looked at your plugin. There is definitely room for improvement on
> the Leiningen side of things in appengine-magic. At the moment,
> Leiningen2 support is simply broken in master, and your plugin seems
> like a step in the right direction.
> 
> I am not a huge fan of splitting appengine-magic into several pieces.
> If your plugin helps resolve the current problems, why not just use it
> to replace the current one?

That'd be fine with me, once it's a little more battle-tested.  Overall
I was actually thinking more conceptually rather than splitting the repo - the basic elements are:

```
lib - api stuff only
server 
tools - i.e. a leiningen plugin with whatever commands are useful - running a devserver, maybe fetching logs from production, etc.
```

and leiningen 2 makes it easy to keep thing cleanly partitioned.  Whether it is better to keep things in one repo or not is another question.  I guess the main thing would be to allow users to pick the parts they want - e.g. somebody might want to use the appengine-magic "lib" (api) but use a different dev server (assuming there were such a thing).  That could be managed with different project files in a single repo, I suppose, like ring does it.

> I didn't dive into lein2 yet, but is there

Lein2 is wonderful.  I don't know how things worked with version 1, but you can quickly see how templates and plugins work in version 2 by doing "lein new template foo" and "lein new plugin bar".  It's amazingly simple.  That and the profiles are really powerful.

> a way to generate two separate artifacts from one project, one with
> just leiningen tasks and one with the App Engine library?

Seems it ought to be possible; projects like ring do something like this.  I'll look into it.

Cheers,

Gregg
