### ISSUE TITLE
ae/start seems to  make slime unresponsive

### ISSUE THREAD

**Issue by thorwil** [gcv/appengine-magic#9]
I looks like using ae/start in an Emacs/slime session causes the repl to become unresponsive. It even happens if I make use of a separate "lein repl".

**Comment by gcv** [comment]
This happens if Emacs has a stale swank connection. The problem probably occurs even if you evaluate something completely unrelated to appengine-magic (e.g., "(+ 3 3)"). I suggest that you restart Emacs and kill any potentially stale JVM processes.

**Comment by thorwil** [comment]
It always seemed to happen shortly after using ae/start, but now I see it happening with virtually nothing going on, too. Sorry.
